CREATE TABLE Ressources (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_ressource VARCHAR(20),
  nom_ressource VARCHAR(750),
  id_parcours VARCHAR(10),
  annee INT,
  semestre VARCHAR(5),
  type VARCHAR(10),
  extension ENUM('jpg', 'jpeg', 'png', 'gif', 'webp') DEFAULT NULL
);

INSERT INTO Ressources (id_ressource, nom_ressource, id_parcours, annee, semestre, type) VALUES
('R101', 'Anglais', 'MMI', 1, 'S1', 'Ressource'),
('R102', 'ESPAGNOL LV2', 'MMI', 1, 'S1', 'Ressource'),
('R103', 'Ergonomie et Accessibilité', 'MMI', 1, 'S1', 'Ressource'),
('R104', 'Culture numérique', 'MMI', 1, 'S1', 'Ressource'),
('R105', 'Stratégie de communication et marketing', 'MMI', 1, 'S1', 'Ressource'),
('R106', 'Expression, communication et rhétorique', 'MMI', 1, 'S1', 'Ressource'),
('R107', 'Ecriture Multimédia et Narration', 'MMI', 1, 'S1', 'Ressource'),
('R108', 'Production graphique', 'MMI', 1, 'S1', 'Ressource'),
('R109', 'Culture artistique', 'MMI', 1, 'S1', 'Ressource'),
('R110', 'Production audio et vidéo', 'MMI', 1, 'S1', 'Ressource'),
('R111', 'Intégration', 'MMI', 1, 'S1', 'Ressource'),
('R112', 'Développement Web', 'MMI', 1, 'S1', 'Ressource'),
('R113', 'Hébergement', 'MMI', 1, 'S1', 'Ressource'),
('R114', 'Représentation et traitement de l''information', 'MMI', 1, 'S1', 'Ressource'),
('R115', 'Gestion de projet', 'MMI', 1, 'S1', 'Ressource'),
('R116', 'Economie, gestion et droit du numérique', 'MMI', 1, 'S1', 'Ressource'),
('R117', 'Projet Personnel et Professionnel', 'MMI', 1, 'S1', 'Ressource'),
('R120', 'Harmonisation Scientifique', 'MMI', 1, 'S1', 'Ressource'),
('SAE101', 'Auditer communication numérique', 'MMI', 1, 'S1', 'SAE'),
('SAE102', 'Concevoir une recommandation de communication numérique', 'MMI', 1, 'S1', 'SAE'),
('SAE103', 'Produire les éléments d''une communication visuelle', 'MMI', 1, 'S1', 'SAE'),
('SAE104', 'Produire un contenu audio et vidéo', 'MMI', 1, 'S1', 'SAE'),
('SAE105', 'Produire un site web', 'MMI', 1, 'S1', 'SAE'),
('SAE106', 'Gérer un projet de communication numérique', 'MMI', 1, 'S1', 'SAE'),
('R202', 'Langue Vivante 2', 'MMI', 1, 'S2', 'Ressource'),
('R203', 'Ergonomie et Accessibilité', 'MMI', 1, 'S2', 'Ressource'),
('R204', 'Culture Numérique', 'MMI', 1, 'S2', 'Ressource'),
('R205', 'Stratégie de communication et marketing', 'MMI', 1, 'S2', 'Ressource'),
('R206', 'Expression, communication et rhétorique', 'MMI', 1, 'S2', 'Ressource'),
('R207', 'Ecriture Multimédia et Narration', 'MMI', 1, 'S2', 'Ressource'),
('R208', 'Production graphique', 'MMI', 1, 'S2', 'Ressource'),
('R209', 'Culture artistique', 'MMI', 1, 'S2', 'Ressource'),
('R210', 'Production audio et vidéo', 'MMI', 1, 'S2', 'Ressource'),
('R211', 'Gestion de contenus', 'MMI', 1, 'S2', 'Ressource'),
('R212', 'Intégration', 'MMI', 1, 'S2', 'Ressource'),
('R213', 'Développement Web', 'MMI', 1, 'S2', 'Ressource'),
('R214', 'Système d''infomation', 'MMI', 1, 'S2', 'Ressource'),
('R215', 'Hébergement', 'MMI', 1, 'S2', 'Ressource'),
('R216', 'Représentation et traitement de l''information', 'MMI', 1, 'S2', 'Ressource'),
('R217', 'Gestion de projet', 'MMI', 1, 'S2', 'Ressource'),
('R218', 'Economie, gestion et droit du numérique', 'MMI', 1, 'S2', 'Ressource'),
('R219', 'Projet Personnel et Professionnel', 'MMI', 1, 'S2', 'Ressource'),
('R201', 'Anglais', 'MMI', 1, 'S2', 'Ressource'),
('SAE201', 'Explorer les usages du numérique', 'MMI', 1, 'S2', 'SAE'),
('SAE202', 'Concevoir un produit ou un service et sa communication', 'MMI', 1, 'S2', 'SAE'),
('SAE203', 'Concevoir un site web avec une source de données', 'MMI', 1, 'S2', 'SAE'),
('SAE204', 'Construire sa présence en ligne', 'MMI', 1, 'S2', 'SAE'),
('R301', 'Anglais', 'MMI', 2, 'S3', 'Ressource'),
('R303', 'Design d''expérience', 'MMI', 2, 'S3', 'Ressource'),
('R304', 'Culture numérique', 'MMI', 2, 'S3', 'Ressource'),
('R305', 'Stratégies de communication et marketing', 'MMI', 2, 'S3', 'Ressource'),
('R306', 'Référencement', 'MMI', 2, 'S3', 'Ressource'),
('R307', 'Expression, communication et rhétorique', 'MMI', 2, 'S3', 'Ressource'),
('R308', 'Écriture multimédia et narration', 'MMI', 2, 'S3', 'Ressource'),
('R309', 'Création et design interactif (UI)', 'MMI', 2, 'S3', 'Ressource'),
('R310', 'Culture artistique', 'MMI', 2, 'S3', 'Ressource'),
('R311', 'Audiovisuel et Motion design', 'MMI', 2, 'S3', 'Ressource'),
('R312', 'Développement Front et intégration', 'MMI', 2, 'S3', 'Ressource'),
('R313', 'CMS avancée, Developpement Back-end', 'MMI', 2, 'S3', 'Ressource'),
('R314', 'Déploiement de services', 'MMI', 2, 'S3', 'Ressource'),
('R315', 'Représentation et traitement de l''information', 'MMI', 2, 'S3', 'Ressource'),
('R316', 'Gestion de projet', 'MMI', 2, 'S3', 'Ressource'),
('R317', 'Economie, gestion et droit du numérique', 'MMI', 2, 'S3', 'Ressource'),
('R318', 'Projet Personnel et Professionnel', 'MMI', 2, 'S3', 'Ressource'),
('R319', 'Soutien PHP', 'MMI', 2, 'S3', 'Ressource'),
('R320', 'Ateliers de rentrée, Remise à niveau', 'MMI', 2, 'S3', 'Ressource'),
('R301', '- Anglais', 'MMI', 2, 'S3', 'Ressource'),
('SAE301', 'Intégrer des interfaces utilisateurs au sein d''un système d''information', 'MMI', 2, 'S3', 'SAE'),
('SAE302', 'Produire des contenus pour une communication plurimédia', 'MMI', 2, 'S3', 'SAE'),
('SAE303', 'Concevoir des visualisations de données pour le web et un support animé', 'MMI', 2, 'S3', 'SAE'),
('R402', 'Economie, gestion et Droit du numérique', 'MMI', 2, 'S4', 'Ressource'),
('R403', 'Design d''expérience', 'MMI', 2, 'S4', 'Ressource'),
('R404', 'Expression, communication', 'MMI', 2, 'S4', 'Ressource'),
('SAE498', 'Hackathon', 'MMI', 2, 'S4', 'SAE'),
('R502', 'Management et assurance qualité', 'MMI', 3, 'S5', 'Ressource'),
('R503', 'Entrepreneuriat', 'MMI', 3, 'S5', 'Ressource'),
('R504', 'Projet Personnel et Professionnel', 'MMI', 3, 'S5', 'Ressource'),
('R505-C', 'Définir une direction artistique', 'MMI', 3, 'S5', 'Ressource'),
('R505-D', 'Développement Front avancé', 'MMI', 3, 'S5', 'Ressource'),
('R506-C', 'Création Numérique', 'MMI', 3, 'S5', 'Ressource'),
('R506-D', 'Développement Back avancé', 'MMI', 3, 'S5', 'Ressource'),
('R507-C', 'Écriture Multimédia et narration', 'MMI', 3, 'S5', 'Ressource'),
('R507-D', 'Dispositifs interactifs', 'MMI', 3, 'S5', 'Ressource'),
('R508-D', 'Hébergement et cybersécurité', 'MMI', 3, 'S5', 'Ressource'),
('R501', 'Anglais', 'MMI', 3, 'S5', 'Ressource'),
('SAE501-C', 'Créer par/pour le numérique', 'MMI', 3, 'S5', 'SAE'),
('SAE502-C', 'Management', 'MMI', 3, 'S5', 'SAE'),
('SAE501-D', 'Développer pour le Web ou concevoir un dispositif interactif', 'MMI', 3, 'S5', 'SAE'),
('SAE502-D', 'Management', 'MMI', 3, 'S5', 'SAE'),
('R601', 'Entrepreneuriat', 'MMI', 3, 'S6', 'Ressource'),
('R602-C', 'Création numérique interactive', 'MMI', 3, 'S6', 'Ressource'),
('R602-D', 'Développement web et dispositif interactif', 'MMI', 3, 'S6', 'Ressource'),
('SAE601-C', 'Créer par/pour le numérique', 'MMI', 3, 'S6', 'SAE'),
('SAE601-D', 'Developpement avancé', 'MMI', 3, 'S6', 'SAE'),
('R1101', 'Acteurs de la société civile', 'CS', 1, 'S1', 'Ressource'),
('R1102', 'Analyse de la société', 'CS', 1, 'S1', 'Ressource'),
('R1103', 'Enjeux contemporains', 'CS', 1, 'S1', 'Ressource'),
('R1202', 'Analyse de la société et des populations', 'CS', 1, 'S1', 'Ressource'),
('R1203', 'Publics et problématiques spécifiques', 'CS', 1, 'S1', 'Ressource'),
('SAE111', '- Entrer en relation avec des acteurs d''un champ professionnel', 'CS', 1, 'S1', 'SAE'),
('SAE121', '- S''initier aux démarches d''enquête ou de diagnostic de territoire', 'CS', 1, 'S1', 'SAE'),
('R2104', 'Principes généraux du droit', 'CS', 1, 'S2', 'Ressource'),
('R2105', 'Cadre politique et institutionnel', 'CS', 1, 'S2', 'Ressource'),
('R2106', 'Projet Professionnel et Personnel', 'CS', 1, 'S2', 'Ressource'),
('R2204', 'Environnement économique', 'CS', 1, 'S2', 'Ressource'),
('R2206', 'Projet Professionnel et Personnel', 'CS', 1, 'S2', 'Ressource'),
('SAE223', '- Organiser une rencontre avec des acteurs du champ professionnel', 'CS', 1, 'S2', 'SAE'),
('R1301', 'Analyse de la société et des populations', 'CS', 2, 'S1', 'Ressource'),
('R1302', 'Méthodologie de la recherche en sciences humaines et sociales', 'CS', 2, 'S1', 'Ressource'),
('R1401', 'Analyse de la société et des populations', 'CS', 2, 'S1', 'Ressource'),
('R1402', 'Publics spécifiques et enjeux de l''intervention sociale', 'CS', 2, 'S1', 'Ressource'),
('S131', 'Réaliser un travail de recherche exploratoire en sciences humaines et sociales', 'CS', 2, 'S1', 'SAE'),
('S141', 'Réaliser un travail de recherche exploratoire en sciences humaines et sociales', 'CS', 2, 'S1', 'SAE'),
('R2303', 'Droit et éthique du travail', 'CS', 2, 'S2', 'Ressource'),
('R2304', 'Politiques publiques', 'CS', 2, 'S2', 'Ressource'),
('R2305', 'Langues et cultures étrangères', 'CS', 2, 'S2', 'Ressource'),
('R2306', 'Projet Professionnel et Personnel', 'CS', 2, 'S2', 'Ressource'),
('R2403', 'Problématiques économiques et sociales', 'CS', 2, 'S2', 'Ressource'),
('R2404', 'Organisation et démarche partenariale', 'CS', 2, 'S2', 'Ressource'),
('R2405', 'Langues et cultures étrangères', 'CS', 2, 'S2', 'Ressource'),
('R2406', 'Projet Professionnel et Personnel', 'CS', 2, 'S2', 'Ressource'),
('S233', 'Expérimenter et analyser une démarche partenariale', 'CS', 2, 'S2', 'SAE'),
('S243', 'Expérimenter et organiser une démarche partenariale', 'CS', 2, 'S2', 'SAE'),
('R101', 'Initiation aux réseaux informatiques', 'RT', 1, 'S1', 'Ressource'),
('R102', 'Principes et architecture des réseaux', 'RT', 1, 'S1', 'Ressource'),
('R103', 'Réseaux locaux et équipements actifs', 'RT', 1, 'S1', 'Ressource'),
('R104', 'Fondamentaux des systèmes électroniques', 'RT', 1, 'S1', 'Ressource'),
('R105', 'Supports de transmission pour les réseaux locaux', 'RT', 1, 'S1', 'Ressource'),
('R106', 'Architecture des systèmes numériques et informatiques', 'RT', 1, 'S1', 'Ressource'),
('R107', 'Fondamentaux de la programmation', 'RT', 1, 'S1', 'Ressource'),
('R108', 'Bases des systèmes d’exploitation', 'RT', 1, 'S1', 'Ressource'),
('R109', 'Introduction aux technologies Web', 'RT', 1, 'S1', 'Ressource'),
('R111', 'Expression-Culture-Communication Professionnelles 1', 'RT', 1, 'S1', 'Ressource'),
('R112', 'Projet Personnel et Professionnel 1', 'RT', 1, 'S1', 'Ressource'),
('R113', 'Mathématiques du signal', 'RT', 1, 'S1', 'Ressource'),
('R114', 'Mathématiques des transmissions', 'RT', 1, 'S1', 'Ressource'),
('R115', 'Gestion de projet', 'RT', 1, 'S1', 'Ressource'),
('R120', '- R220 Outils pour l''ingénierie', 'RT', 1, 'S1', 'Ressource'),
('R121', 'Télécommunications spatiales', 'RT', 1, 'S1', 'Ressource'),
('R110', '- Anglais', 'RT', 1, 'S1', 'Ressource'),
('SAE11', 'Se sensibiliser à l’hygiène informatique et à la cybersécurité', 'RT', 1, 'S1', 'SAE'),
('SAE12', 'S’initier aux réseaux informatiques', 'RT', 1, 'S1', 'SAE'),
('SAE13', 'Découvrir un dispositif de transmission', 'RT', 1, 'S1', 'SAE'),
('SAE14', 'Se présenter sur Internet', 'RT', 1, 'S1', 'SAE'),
('SAE15', 'Traiter des données', 'RT', 1, 'S1', 'SAE'),
('R201', 'Technologie de l’Internet', 'RT', 1, 'S2', 'Ressource'),
('R202', 'Administration système et fondamentaux de la virtualisation', 'RT', 1, 'S2', 'Ressource'),
('R203', 'Bases des services réseaux', 'RT', 1, 'S2', 'Ressource'),
('R204', 'Initiation à la téléphonie d’entreprise', 'RT', 1, 'S2', 'Ressource'),
('R205', 'Signaux et Systèmes pour les transmissions', 'RT', 1, 'S2', 'Ressource'),
('R206', 'Numérisation de l’information', 'RT', 1, 'S2', 'Ressource'),
('R207', 'Sources de données', 'RT', 1, 'S2', 'Ressource'),
('R208', 'Analyse et traitement de données structurées', 'RT', 1, 'S2', 'Ressource'),
('R209', 'Initiation au développement Web', 'RT', 1, 'S2', 'Ressource'),
('R211', 'Expression-Culture-Communication Professionnelles 2', 'RT', 1, 'S2', 'Ressource'),
('R212', 'Projet Personnel et Professionnel', 'RT', 1, 'S2', 'Ressource'),
('R213', 'Mathématiques des systèmes numériques', 'RT', 1, 'S2', 'Ressource'),
('R214', 'Analyse mathématique des signaux', 'RT', 1, 'S2', 'Ressource'),
('R220', 'Outils pour l''ingénierie', 'RT', 1, 'S2', 'Ressource'),
('R221', 'Télécommunications spatiales', 'RT', 1, 'S2', 'Ressource'),
('R210', '- Anglais', 'RT', 1, 'S2', 'Ressource'),
('SAE21', 'Construire un réseau informatique pour une petite structure', 'RT', 1, 'S2', 'SAE'),
('SAE22', 'Mesurer et caractériser un signal ou un système', 'RT', 1, 'S2', 'SAE'),
('SAE23', 'Mettre en place une solution informatique pour l’entreprise', 'RT', 1, 'S2', 'SAE'),
('SAE24', 'Projet intégratif', 'RT', 1, 'S2', 'SAE'),
('R301', 'Réseaux de campus', 'RT', 2, 'S3', 'Ressource'),
('R302', 'Réseaux opérateurs', 'RT', 2, 'S3', 'Ressource'),
('R303', 'Services réseaux avancés', 'RT', 2, 'S3', 'Ressource'),
('R304', 'Services d’annuaires', 'RT', 2, 'S3', 'Ressource'),
('R305', 'Chaînes de transmissions numériques', 'RT', 2, 'S3', 'Ressource'),
('R306', 'Fibres optiques et propagation', 'RT', 2, 'S3', 'Ressource'),
('R307', 'Réseaux d’accès', 'RT', 2, 'S3', 'Ressource'),
('R308', 'Consolidation de la programmation', 'RT', 2, 'S3', 'Ressource'),
('R309', 'Programmation évènementielle', 'RT', 2, 'S3', 'Ressource'),
('R310', 'Gestion d’un système de bases de données', 'RT', 2, 'S3', 'Ressource'),
('R311', 'Anglais professionnel 1', 'RT', 2, 'S3', 'Ressource'),
('R312', 'Expression-Culture-Communication pro 3', 'RT', 2, 'S3', 'Ressource'),
('R313', 'PPP', 'RT', 2, 'S3', 'Ressource'),
('R314', 'Analyse de Fourier', 'RT', 2, 'S3', 'Ressource'),
('R315', 'Gestion de Projet', 'RT', 2, 'S3', 'Ressource'),
('R316-C', 'Méthodologie du pentesting', 'RT', 2, 'S3', 'Ressource'),
('R316-D', 'Ecosystème Cloud', 'RT', 2, 'S3', 'Ressource'),
('R316-I', 'Introduction à l’Internet des Objets', 'RT', 2, 'S3', 'Ressource'),
('R317-D', 'Virtualisation avancée', 'RT', 2, 'S3', 'Ressource'),
('R317-I', 'Collecte et traitement de données issues IoT', 'RT', 2, 'S3', 'Ressource'),
('SAE301', 'Mettre en œuvre un système de transmission', 'RT', 2, 'S3', 'SAE'),
('SAE302', 'Développer des applications communicantes', 'RT', 2, 'S3', 'SAE'),
('SAE303-C', 'Concevoir un réseau informatique sécurisé multi-sites', 'RT', 2, 'S3', 'SAE'),
('SAE303-D', 'Concevoir un réseau informatique multi-sites hébergeant des services virtualisés', 'RT', 2, 'S3', 'SAE'),
('SAE303-I', 'Concevoir un réseau multi-sites intégrant des objets connectés', 'RT', 2, 'S3', 'SAE'),
('SAE304-C', 'Découvrir le pentesting', 'RT', 2, 'S3', 'SAE'),
('SAE304-D', 'Mettre en place une infrastructure virtualisée', 'RT', 2, 'S3', 'SAE'),
('SAE304-I', 'Découvrir et mettre en place un réseau IoT', 'RT', 2, 'S3', 'SAE'),
('R401', ': Infrastructures de sécurité', 'RT', 2, 'S4', 'Ressource'),
('R402', 'Transmissions avancées', 'RT', 2, 'S4', 'Ressource'),
('R403', 'Physique des télécoms', 'RT', 2, 'S4', 'Ressource'),
('R404', 'Réseaux cellulaires', 'RT', 2, 'S4', 'Ressource'),
('R405', 'Automatisation des tâches d’administration', 'RT', 2, 'S4', 'Ressource'),
('R406', 'Anglais professionnel 2', 'RT', 2, 'S4', 'Ressource'),
('R407', 'Expression-Culture-Communication professionnelles', 'RT', 2, 'S4', 'Ressource'),
('R408', 'Projet Personnel et Professionnel', 'RT', 2, 'S4', 'Ressource'),
('R409-C', 'Sécurité des réseaux LAN', 'RT', 2, 'S4', 'Ressource'),
('R409-D', 'Fondamentaux de la conteneurisation', 'RT', 2, 'S4', 'Ressource'),
('R409-I', 'Réseaux sans fil pour l’IoT : MAC et routage', 'RT', 2, 'S4', 'Ressource'),
('R410-C', 'Cryptographie', 'RT', 2, 'S4', 'Ressource'),
('R410-D', 'Développement de microservices', 'RT', 2, 'S4', 'Ressource'),
('R410-I', 'Cryptographie', 'RT', 2, 'S4', 'Ressource'),
('R411-C', 'Sécurisation de services réseaux', 'RT', 2, 'S4', 'Ressource'),
('R411-I', 'Réseaux sans fil pour l’IoT : couche phy', 'RT', 2, 'S4', 'Ressource'),
('R420', 'Outils pour l''ingénierie', 'RT', 2, 'S4', 'Ressource'),
('R421', 'Télécommunications spatiales', 'RT', 2, 'S4', 'Ressource'),
('R406', 'If I Were...!', 'RT', 2, 'S4', 'Ressource'),
('SAE401-C', 'Sécuriser un système d’information', 'RT', 2, 'S4', 'SAE'),
('SAE401-D', 'Développer et déployer un microservice dans un environnement virtualisé', 'RT', 2, 'S4', 'SAE'),
('SAE401-I', ': Implémenter les réseaux et protocoles sans fil dédiés à l’IoT', 'RT', 2, 'S4', 'SAE'),
('R501', 'Wifi Avancé', 'RT', 3, 'S5', 'Ressource'),
('R502', 'Supervision des réseaux', 'RT', 3, 'S5', 'Ressource'),
('R503', 'Ingénierie des systèmes télécoms', 'RT', 3, 'S5', 'Ressource'),
('R504', 'cycle de vie d''un projet informatique', 'RT', 3, 'S5', 'Ressource'),
('R505', 'Anglais, insertion professionnelle 1', 'RT', 3, 'S5', 'Ressource'),
('R506', 'Expression, culture, communication professionnelles', 'RT', 3, 'S5', 'Ressource'),
('R507', 'Projet Personnel Professionnel', 'RT', 3, 'S5', 'Ressource'),
('R508', 'Gestion de projets 3', 'RT', 3, 'S5', 'Ressource'),
('R509-C', 'Architectures sécurisées', 'RT', 3, 'S5', 'Ressource'),
('R509-D', 'Outils et méthodes du DevOps', 'RT', 3, 'S5', 'Ressource'),
('R510-D', 'Infrastructures conteneurisées', 'RT', 3, 'S5', 'Ressource'),
('R510-I', 'Cryptographie', 'RT', 3, 'S5', 'Ressource'),
('R511-C', 'Supervision de la sécurité', 'RT', 3, 'S5', 'Ressource'),
('R511-D', 'Programmer son infrastructure', 'RT', 3, 'S5', 'Ressource'),
('R511-I', 'Réseaux sans fil pour l''IoT: couche physique', 'RT', 3, 'S5', 'Ressource'),
('R512-C', 'Normes, standards et analyse de risques', 'RT', 3, 'S5', 'Ressource'),
('R512-D', 'Solutions Cloud', 'RT', 3, 'S5', 'Ressource'),
('R520', 'Outils pour l''ingénieurie', 'RT', 3, 'S5', 'Ressource'),
('R510-C', 'Audit', 'RT', 3, 'S5', 'Ressource'),
('SAE501', 'concevoir, réaliser et présenter une solution technique', 'RT', 3, 'S5', 'SAE'),
('SAE502', 'Piloter un projet informatique', 'RT', 3, 'S5', 'SAE'),
('SAE503-C', 'Assurer la sécurisation et la supervision avancées d''un système d''information', 'RT', 3, 'S5', 'SAE'),
('SAE503-D', 'Orchestrer la conteneurisation d''une application', 'RT', 3, 'S5', 'SAE'),
('SAE503-I', 'Qualifier les architectures de réseaux hybrides dédiées à l''IoT', 'RT', 3, 'S5', 'SAE'),
('R601', 'Anglais, insertion professionnelle 2', 'RT', 3, 'S6', 'Ressource'),
('R602', 'Expression, culture, communication professionnelles, communiquer en tant que futur cadre intermédiaire', 'RT', 3, 'S6', 'Ressource'),
('R603', 'Connaissance de l''entreprise', 'RT', 3, 'S6', 'Ressource'),
('R604-C', 'Réponse à incident', 'RT', 3, 'S6', 'Ressource'),
('R604-D', 'Pilotage de solutions cloud pour l''entreprise', 'RT', 3, 'S6', 'Ressource'),
('R604-I', 'Chaînes complètes IoM', 'RT', 3, 'S6', 'Ressource'),
('R621', 'Télécommunications spatiales', 'RT', 3, 'S6', 'Ressource'),
('SAE601-C', 'Réagir face à une cyber-attaque', 'RT', 3, 'S6', 'SAE'),
('SAE601-D', 'Gérer le pipeline d''une application orientée Cloud', 'RT', 3, 'S6', 'SAE'),
('SAE601-I', 'Mettre en place un réseau IoT répondant à un cahier des charges', 'RT', 3, 'S6', 'SAE'),
('R101', 'Fondamentaux du marketing et comportement du consommateur', 'TC', 1, 'S1', 'Ressource'),
('R102', 'Fondamentaux de la vente', 'TC', 1, 'S1', 'Ressource'),
('R103', 'Fondamentaux de la communication commerciale', 'TC', 1, 'S1', 'Ressource'),
('R104', 'Études  Marketing  1', 'TC', 1, 'S1', 'Ressource'),
('R105', 'Environnement juridique de l''entreprise', 'TC', 1, 'S1', 'Ressource'),
('R106', 'Environnement  économique  de l’entreprise', 'TC', 1, 'S1', 'Ressource'),
('R107', 'Techniques quantitatives et représentations 1', 'TC', 1, 'S1', 'Ressource'),
('R108', 'Eléments financiers de l’entreprise', 'TC', 1, 'S1', 'Ressource'),
('R109', 'Rôle et organisation de l’entreprise sur son marché', 'TC', 1, 'S1', 'Ressource'),
('R110', 'Initiation à la conduite de projet', 'TC', 1, 'S1', 'Ressource'),
('R111', 'Anglais du commerce', 'TC', 1, 'S1', 'Ressource'),
('R112', 'Langues B du commerce', 'TC', 1, 'S1', 'Ressource'),
('R113', 'Ressources et culture numériques', 'TC', 1, 'S1', 'Ressource'),
('R114', 'Expression, communication et culture 1', 'TC', 1, 'S1', 'Ressource'),
('R115', 'PPP', 'TC', 1, 'S1', 'Ressource'),
('SAE101', 'Marketing : Positionnement d''une offre simple sur un marché', 'TC', 1, 'S1', 'SAE'),
('SAE102', 'Vente : démarche de prospection', 'TC', 1, 'S1', 'SAE'),
('SAE103', 'Communication commerciale : Création d''un support "print"', 'TC', 1, 'S1', 'SAE'),
('R201', 'Marketing mix', 'TC', 1, 'S2', 'Ressource'),
('R202', 'Prospection et négociation', 'TC', 1, 'S2', 'Ressource'),
('R203', 'Moyens de la communication commerciale', 'TC', 1, 'S2', 'Ressource'),
('R204', 'Étude Marketing 2', 'TC', 1, 'S2', 'Ressource'),
('R205', 'Relations contractuelles commerciales', 'TC', 1, 'S2', 'Ressource'),
('R206', 'Techniques quantitatives et représentations 2', 'TC', 1, 'S2', 'Ressource'),
('R207', 'Coûts, marges et prix d’une offre simple', 'TC', 1, 'S2', 'Ressource'),
('R208', 'Connaissance des canaux de commercialisation et distribution', 'TC', 1, 'S2', 'Ressource'),
('R209', 'Psychologie sociale', 'TC', 1, 'S2', 'Ressource'),
('R210', 'Gestion et conduite de projet', 'TC', 1, 'S2', 'Ressource'),
('R211', 'Anglais appliqué au commerce', 'TC', 1, 'S2', 'Ressource'),
('R212', 'Langue 2 appliquée au commerce', 'TC', 1, 'S2', 'Ressource'),
('R213', 'Ressources et culture numériques 2', 'TC', 1, 'S2', 'Ressource'),
('R214', 'Expression, communication et culture 2', 'TC', 1, 'S2', 'Ressource'),
('R215', 'PPP 2', 'TC', 1, 'S2', 'Ressource'),
('SAE201', 'Marketing générique', 'TC', 1, 'S2', 'SAE'),
('SAE202', 'Vente : Initiation au jeu de rôle de négociation', 'TC', 1, 'S2', 'SAE'),
('SAE203', 'Communication commerciale : élaboration d''un plan de com. Commerciale', 'TC', 1, 'S2', 'SAE'),
('SAE204', 'Conception d''un projet déployant les techniques de Com', 'TC', 1, 'S2', 'SAE'),
('SAE205', 'STAGE S2', 'TC', 1, 'S2', 'SAE'),
('R301', 'Marketing Mix - 2', 'TC', 2, 'S3', 'Ressource'),
('R302', 'Entretien de vente', 'TC', 2, 'S3', 'Ressource'),
('R303', 'Principes de la communication digitale', 'TC', 2, 'S3', 'Ressource'),
('R304', 'Etudes marketing - 3', 'TC', 2, 'S3', 'Ressource'),
('R305', 'Environnement économique international', 'TC', 2, 'S3', 'Ressource'),
('R306', 'Droit des activités commerciales - 1', 'TC', 2, 'S3', 'Ressource'),
('R307', 'Techniques quantitatives et représentations - 3', 'TC', 2, 'S3', 'Ressource'),
('R308', 'Tableau de bord commercial', 'TC', 2, 'S3', 'Ressource'),
('R309', 'Psychologie Sociale du travail', 'TC', 2, 'S3', 'Ressource'),
('R310', 'Anglais appliqué au commerce - 3', 'TC', 2, 'S3', 'Ressource'),
('R311-E', 'LV2 Espagnol', 'TC', 2, 'S3', 'Ressource'),
('R311', 'LV2 Appliquée au commerce - 3', 'TC', 2, 'S3', 'Ressource'),
('R312-MDEE', 'Ressources  et cultures numériques', 'TC', 2, 'S3', 'Ressource'),
('R312', 'Ressources et culture numériques - 3', 'TC', 2, 'S3', 'Ressource'),
('R313-MMPV', 'Expression, communication, culture - 3', 'TC', 2, 'S3', 'Ressource'),
('R313-MDEE', 'Expression, communication, culture - 3', 'TC', 2, 'S3', 'Ressource'),
('R314', 'PPP - 3', 'TC', 2, 'S3', 'Ressource'),
('R315-MDEE', 'Stratégie de marketing digital', 'TC', 2, 'S3', 'Ressource'),
('R315-BI', 'Stratégie et veille à l''international', 'TC', 2, 'S3', 'Ressource'),
('SAE31', 'Piloter un projet en déployant les techniques de commercialisation', 'TC', 2, 'S3', 'SAE'),
('SAE301', 'Projets Apprentis', 'TC', 2, 'S3', 'SAE'),
('SAE302-BI', 'Démarche de création d''entreprise à l''international', 'TC', 2, 'S3', 'SAE'),
('SAE303-BI', 'Etude et sélection des marchés à l''étranger pour déployer l''offre', 'TC', 2, 'S3', 'SAE'),
('SAE302-MDEE', 'Démarche de création d''entreprise en contexte digital', 'TC', 2, 'S3', 'SAE'),
('SAE303-MDEE', 'Analyse d''une activité digitale', 'TC', 2, 'S3', 'SAE'),
('SAE302-MMPV', 'Démarche d''ouverture d''un point de vente', 'TC', 2, 'S3', 'SAE'),
('SAE303-MMPV', 'Analyse d''un point de vente ou d''un rayon dans un environnement concurrentiel', 'TC', 2, 'S3', 'SAE'),
('R401', 'Stratégie marketing', 'TC', 2, 'S4', 'Ressource'),
('R402', 'Négociation : rôle du vendeur et de l’acheteur', 'TC', 2, 'S4', 'Ressource'),
('R403', 'Conception d’une campagne de communication', 'TC', 2, 'S4', 'Ressource'),
('R404', 'Droit du travail', 'TC', 2, 'S4', 'Ressource'),
('R405', 'Anglais appliqué au commerce - 4', 'TC', 2, 'S4', 'Ressource'),
('R406', 'LV B appliquée au commerce - 4', 'TC', 2, 'S4', 'Ressource'),
('R407', 'Expression, communication, culture - 4', 'TC', 2, 'S4', 'Ressource'),
('R408', 'PPP', 'TC', 2, 'S4', 'Ressource'),
('R409-BI', 'Stratégie achats', 'TC', 2, 'S4', 'Ressource'),
('R409-MDEE', 'Conduite de projet digital', 'TC', 2, 'S4', 'Ressource'),
('R409-MMPV', 'Merchandising', 'TC', 2, 'S4', 'Ressource'),
('R410-BI', 'Techniques de commercialisation 1', 'TC', 2, 'S4', 'Ressource'),
('R410-MMPV', 'Management des équipes 1', 'TC', 2, 'S4', 'Ressource'),
('R411-BI', 'management interculturel', 'TC', 2, 'S4', 'Ressource'),
('R411-MMPV', 'GRC', 'TC', 2, 'S4', 'Ressource'),
('SAE401', 'Evaluer la performance du projet en déployant les T de C', 'TC', 2, 'S4', 'SAE'),
('SAE402', 'Pilotage commercial d''une organisation', 'TC', 2, 'S4', 'SAE'),
('SAE403-BI', 'Développement de l''offre à l''international', 'TC', 2, 'S4', 'SAE'),
('SAE403-MMPV', 'Propositions d''amélioration du fonctionnement du point de vente et du management de l''équipe', 'TC', 2, 'S4', 'SAE'),
('SAE403-MDEE', 'Création de site web', 'TC', 2, 'S4', 'SAE'),
('R520', ': Systèmes Agroalimentaires Durables', 'TC', 3, 'S5', 'Ressource'),
('R521', ': Anglais Renforcé', 'TC', 3, 'S5', 'Ressource'),
('R315-MMPV', 'Management de la performance du point de vente', 'TC', 2, 'S3', 'Ressource'),
('R316-MDEE', 'Créativité et innovation', 'TC', 2, 'S3', 'Ressource'),
('R316-BI', "Marketing et vente à l'international", 'TC', 2, 'S3', 'Ressource'),
('R316-MMPV', 'Marketing du point de vente', 'TC', 2, 'S3', 'Ressource'),
('R317', 'Apprendre autrement', 'TC', 2, 'S3', 'Ressource'),
('R318', "Apprendre l'écosystème économique et/ou biterrois", 'TC', 2, 'S3', 'Ressource'),
('R101', 'English', 'ROBIA', 1, 'S1', 'Ressource'),
('R103', "Mathématiques pour l\'IT", 'ROBIA', 1, 'S1', 'Ressource'),
('R105', 'Physique Appliquée Circuits Electriques', 'ROBIA', 1, 'S1', 'Ressource'),
('R107', 'Programmation Algorithmique', 'ROBIA', 1, 'S1', 'Ressource'),
('R109', 'Initiation aux réseaux', 'ROBIA', 1, 'S1', 'Ressource'),
('R111', 'Cybersécurité et Hygiène Informatique', 'ROBIA', 1, 'S1', 'Ressource'),
('R113', 'Intelligence Artificielle', 'ROBIA', 1, 'S1', 'Ressource'),
('R115', 'Instrumentation Métrologie', 'ROBIA', 1, 'S1', 'Ressource'),
('R117', 'Régulation et Asservissements - Initiation', 'ROBIA', 1, 'S1', 'Ressource'),
('R119', 'Automatismes Logique', 'ROBIA', 1, 'S1', 'Ressource'),
('R120', 'Automatismes - Structures et Raccordements des API', 'ROBIA', 1, 'S1', 'Ressource'),
('R121', 'Introduction à la Robotique', 'ROBIA', 1, 'S1', 'Ressource'),
('R122', 'Caractérisation des Robots', 'ROBIA', 1, 'S1', 'Ressource'),
('SAE11', 'Bonnes pratiques de la cybersécurité', 'ROBIA', 1, 'S1', 'SAE'),
('SAE12', 'Apprendre à câbler les capteurs et actionneurs', 'ROBIA', 1, 'S1', 'SAE'),
('SAE13', "Conception d\'une application d\'automatisme ou de robotique", 'ROBIA', 1, 'S1', 'SAE'),
('SAE14', 'Maintenance et gestion du code', 'ROBIA', 1, 'S1', 'SAE'),
('R201', 'Anglais et Communication', 'ROBIA', 1, 'S2', 'Ressource'),
('R204', "Mathématiques pour l\'OT", 'ROBIA', 1, 'S2', 'Ressource'),
('R205', 'Physique Appliquée Analyse fréquentielle', 'ROBIA', 1, 'S2', 'Ressource'),
('R206', 'Physique appliquée, distribution appareillage', 'ROBIA', 1, 'S2', 'Ressource'),
('R207', 'Programmation POO', 'ROBIA', 1, 'S2', 'Ressource'),
('R209', 'Bases des services réseaux', 'ROBIA', 1, 'S2', 'Ressource'),
('R210', 'Télécommunications', 'ROBIA', 1, 'S2', 'Ressource'),
('R211', 'Cybersécurité', 'ROBIA', 1, 'S2', 'Ressource'),
('R213', 'IA Apprentissage supervisé', 'ROBIA', 1, 'S2', 'Ressource'),
('R215', 'Instrumentation Détecteurs TOR', 'ROBIA', 1, 'S2', 'Ressource'),
('R216', 'Instrumentation Pneumatique TOR', 'ROBIA', 1, 'S2', 'Ressource'),
('R217', 'Programmation des régulateurs', 'ROBIA', 1, 'S2', 'Ressource'),
('R218', 'Commande en BF des procédés', 'ROBIA', 1, 'S2', 'Ressource'),
('R219', 'Automatismes Grafcet', 'ROBIA', 1, 'S2', 'Ressource'),
('R221', 'Robotique et Vision Approche pratique', 'ROBIA', 1, 'S2', 'Ressource'),
('R222', 'Vision industrielle', 'ROBIA', 1, 'S2', 'Ressource'),
('SAE21', "Conception et déploiement d\'une solution d\'automatisme", 'ROBIA', 1, 'S2', 'SAE'),
('SAE22', "Conception et déploiement d\'une solution de robotique", 'ROBIA', 1, 'S2', 'SAE'),
('SAE23', "Maintenance et raccordement d\'une application Automatisme ou Robotique", 'ROBIA', 1, 'S2', 'SAE'),
('SAE24', 'Sécurité des applications Automatisme ou Robotique', 'ROBIA', 1, 'S2', 'SAE'),
('SAE25', "Amélioration de la productivité d\'un client", 'ROBIA', 1, 'S2', 'SAE'),
('R301', 'Anglais et communication', 'ROBIA', 2, 'S3', 'Ressource'),
('R303', 'Statistiques inférentielles', 'ROBIA', 2, 'S3', 'Ressource'),
('R304', 'Méca-Maths', 'ROBIA', 2, 'S3', 'Ressource'),
('R305', 'Mécanique des fluides', 'ROBIA', 2, 'S3', 'Ressource'),
('R307', 'Programmation BDD', 'ROBIA', 2, 'S3', 'Ressource'),
('R309', 'Réseaux Locaux Industriels', 'ROBIA', 2, 'S3', 'Ressource'),
('R311', 'Sécurisation des réseaux industriels', 'ROBIA', 2, 'S3', 'Ressource'),
('R313', 'Apprentissage non supervisé', 'ROBIA', 2, 'S3', 'Ressource'),
('R314', 'Apprentissage profond', 'ROBIA', 2, 'S3', 'Ressource'),
('R315', 'Mesures de grandeurs physiques', 'ROBIA', 2, 'S3', 'Ressource'),
('R319', 'Sécurité Machine', 'ROBIA', 2, 'S3', 'Ressource'),
('R321', 'Modélisation des robots', 'ROBIA', 2, 'S3', 'Ressource'),
('SAE31', 'Robotique AGV - Raspblock', 'ROBIA', 2, 'S3', 'SAE'),
('SAE32', 'Robot conversationnel', 'ROBIA', 2, 'S3', 'SAE'),
('SAE33', "Cybersécurité d\'un réseau Industriel", 'ROBIA', 2, 'S3', 'SAE'),
('SAE34', 'Safety', 'ROBIA', 2, 'S3', 'SAE'),
('R401', 'Anglais et Communication', 'ROBIA', 2, 'S4', 'Ressource'),
('R403', "Maths pour l\'IT", 'ROBIA', 2, 'S4', 'Ressource'),
('R404', "Maths pour l\'OT", 'ROBIA', 2, 'S4', 'Ressource'),
('R405', 'Conversion Énergie', 'ROBIA', 2, 'S4', 'Ressource'),
('R407', 'Programmation', 'ROBIA', 2, 'S4', 'Ressource'),
('R409', 'Réseaux Avancés', 'ROBIA', 2, 'S4', 'Ressource'),
('R413', 'Apprentissage sur des séries temporelles', 'ROBIA', 2, 'S4', 'Ressource'),
('R414', 'Apprentissage des séries temporelles', 'ROBIA', 2, 'S4', 'Ressource'),
('R415', 'ATEX', 'ROBIA', 2, 'S4', 'Ressource'),
('R417', 'Stabilité des systèmes en BF', 'ROBIA', 2, 'S4', 'Ressource'),
('R418', 'Scada, Panneau opérateurs, Alarmes', 'ROBIA', 2, 'S4', 'Ressource'),
('R421', 'Modélisation des robots manipulateurs articulés', 'ROBIA', 2, 'S4', 'Ressource'),
('R422', 'Modélisation des caméras, calibration, Mesures 3D, Reconstruction', 'ROBIA', 2, 'S4', 'Ressource'),
('SAE41', 'Internet Industriel des Objets (IIoT)', 'ROBIA', 2, 'S4', 'SAE'),
('SAE42', 'Contrôle Industriel', 'ROBIA', 2, 'S4', 'SAE'),
('SAE44', 'Stages', 'ROBIA', 2, 'S4', 'SAE');